server:
  port: 8080
  error:
    include-message: always

axon:
  eventhandling:
    processors:
      PolicyHandler:
        mode: subscribing

---

spring:
  profiles: default

server:
  port: 8082
---

spring:
  profiles: docker

